### ISSUE TITLE
Multiple Accounts?

### ISSUE THREAD

**Issue by ItIsSeven** [Stovven/twitter-discord-webhook#1]
Does this support multiple accounts, so multiple Twitter ID's, and then the ability to send each twitter ID to a different webhook.
Thank you, it's a feature I really want, & isn't available in other JS projects.

**Comment by Stovven** [comment]
no unfortunately, i can get around to doing it though.

**Comment by ItIsSeven** [comment]
Thank to your nice documentiation with your application, which others don't care to outline, I figured out why the previous I used which has the features I needed wasn't working. I didn't have an Elevated permissions. So I got it working after that.

I don't want you to waste time developing something that I ultimately don't need, but would be a nice addition anyways if you have free time! But thank you for creating this project, nice to see someone got this working in JS aswell!

If you do want to continue adding this feature, feel free to reopen the issue.
